import { useState, type FormEvent } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Eye, EyeOff, Sparkles } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { useApp } from '../App'

export function AuthPage({mode}:{mode:'login'|'signup'}) {
  const {session,tell}=useApp();const navigate=useNavigate();const [busy,setBusy]=useState(false);const [showPassword,setShowPassword]=useState(false);const [error,setError]=useState('')
  if(session)return <Navigate to="/dashboard" replace/>
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));const result=mode==='signup'?await supabase.auth.signUp({email,password,options:{data:{full_name:f.get('name'),role:f.get('role')}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(result.error){setError(result.error.message);return}if(mode==='signup'&&!result.data.session){tell('Vérifiez votre e-mail pour confirmer votre compte.');navigate('/connexion')}else{tell('Ravi de vous retrouver !');navigate('/dashboard')}}
  return <main className="auth-layout"><section className="auth-aside"><Link className="brand auth-brand" to="/"><span className="brand-mark"><Sparkles size={18} fill="currentColor"/></span>forma<i>.</i></Link><div className="auth-story"><span className="auth-quote-mark">“</span><h1>Le meilleur investissement, c’est celui que l’on fait en soi.</h1><p>Apprenez auprès de personnes qui aiment transmettre.</p><div className="auth-proof"><div className="stacked-avatars"><span>AM</span><span>JD</span><span>SL</span><span>+</span></div><span>Une communauté curieuse<br/>et généreuse</span></div></div><div className="auth-aside-bottom"><span>✳</span> APPRENDRE ENSEMBLE, AUTREMENT</div><div className="auth-decoration decor-one"/><div className="auth-decoration decor-two"/></section><section className="auth-main"><Link to="/" className="auth-back"><ArrowLeft size={16}/> Retour à l’accueil</Link><div className="auth-form-wrap"><div className="auth-eyebrow"><BookOpen size={15}/> VOTRE PROCHAIN CHAPITRE</div><h2>{mode==='signup'?'On commence ?':'Heureux de vous revoir.'}</h2><p className="auth-subtitle">{mode==='signup'?'Créez votre compte gratuit, et ouvrez le champ des possibles.':'Connectez-vous pour retrouver vos formations.'}</p><form className="auth-form" onSubmit={submit}>{mode==='signup'&&<><label>Votre nom<input name="name" required placeholder="Ex. Léa Martin" autoComplete="name"/></label><label>Je souhaite<select name="role" defaultValue="student"><option value="student">Apprendre en tant qu’étudiant</option><option value="trainer">Transmettre en tant que formateur</option></select></label></>}<label>Adresse e-mail<input name="email" type="email" required placeholder="vous@exemple.fr" autoComplete="email"/></label><label>Mot de passe<span className="password-wrap"><input name="password" type={showPassword?'text':'password'} minLength={6} required placeholder="6 caractères minimum" autoComplete={mode==='signup'?'new-password':'current-password'}/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label="Afficher le mot de passe">{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></span></label>{mode==='login'&&<button type="button" className="forgot-link" onClick={()=>setError('Pour réinitialiser votre mot de passe, utilisez « Mot de passe oublié » dans les paramètres d’authentification Supabase.')}>Mot de passe oublié ?</button>}{error&&<div className="form-error">{error}</div>}<button className="button button-primary button-wide" disabled={busy}>{busy?'Un instant…':mode==='signup'?'Créer mon compte':'Me connecter'}<ArrowRight size={16}/></button></form><div className="auth-switch">{mode==='signup'?'Vous avez déjà un compte ?':'Nouveau sur Forma ?'} <Link to={mode==='signup'?'/connexion':'/inscription'}>{mode==='signup'?'Se connecter':'Créer un compte'}</Link></div><div className="auth-trust"><CheckCircle2 size={15}/> Vos données restent protégées et ne sont jamais revendues.</div></div></section></main>
}
