import { useEffect, useState, type FormEvent } from 'react'
import { CalendarDays, Clock3, Plus, Video } from 'lucide-react'
import { Link } from 'react-router-dom'
import { supabase, type Course } from '../lib/supabase'
import { useApp } from '../App'
type LiveSession = { id:string; course_id:string; title:string; starts_at:string; duration_minutes:number; courses?:{title:string} }
export function SessionsPanel({courses,isTrainer}:{courses:Course[];isTrainer:boolean}) {
 const {session,tell}=useApp(); const [items,setItems]=useState<LiveSession[]>([]); const [creating,setCreating]=useState(false); const [busy,setBusy]=useState(false); const courseIds=courses.map(c=>c.id)
 async function refresh(){if(!session||!courseIds.length){setItems([]);return} const {data,error}=await supabase.from('live_sessions').select('id,course_id,title,starts_at,duration_minutes,courses(title)').in('course_id',courseIds).gte('starts_at',new Date().toISOString()).eq('status','planned').order('starts_at').limit(5);if(error){tell(error.message);return}setItems((data??[]) as unknown as LiveSession[])}
 useEffect(()=>{void refresh()},[session?.user.id,courseIds.join(',')])
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;setBusy(true);const f=new FormData(e.currentTarget);const {error}=await supabase.from('live_sessions').insert({course_id:String(f.get('course_id')),trainer_id:session.user.id,title:String(f.get('title')),starts_at:new Date(String(f.get('starts_at'))).toISOString(),duration_minutes:Number(f.get('duration_minutes'))});setBusy(false);if(error){tell(error.message);return}setCreating(false);tell('La classe en direct est planifiee.');await refresh()}
 return <div className="scheduled-sessions">{items.length?items.map(item=><article className="scheduled-session" key={item.id}><span className="scheduled-session-icon"><Video size={17}/></span><div className="scheduled-session-info"><b>{item.title}</b><small>{item.courses?.title}</small><span><CalendarDays size={13}/>{new Date(item.starts_at).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'})}<i>·</i><Clock3 size={13}/>{item.duration_minutes} min</span></div><Link className="button button-outline button-compact" to={`/salle/${item.course_id}`}>Rejoindre <Video size={13}/></Link></article>):<div className="upcoming-empty"><span className="calendar-art"><CalendarDays size={22}/></span><b>{isTrainer?'Planifiez votre premiere classe':'Aucune session a venir'}</b><p>{isTrainer?'Invitez vos etudiants a un rendez-vous en direct.':'Les prochaines rencontres en direct apparaitront ici.'}</p></div>}
 {isTrainer&&<button className="add-lesson-button session-create-button" onClick={()=>setCreating(v=>!v)}><Plus size={15}/>{creating?'Fermer':'Planifier une classe'}</button>}
 {creating&&<form className="session-form" onSubmit={create}><label>Formation<select name="course_id" required defaultValue=""><option value="" disabled>Choisir une formation</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Titre de la classe<input name="title" required minLength={3} maxLength={120} placeholder="Ex. Atelier questions / reponses"/></label><div className="form-row"><label>Date et heure<input name="starts_at" type="datetime-local" required min={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/></label><label>Duree (minutes)<input name="duration_minutes" type="number" min="15" max="240" defaultValue="60" required/></label></div><button className="button button-primary button-wide" disabled={busy}>{busy?'Planification...':'Confirmer la session'}</button></form>}</div>
}
